label:
  en: SEO
  nl: SEO
icon: search
columns:
  - width: 3/5
    sections:
      seocontent:
        type: fields
        fields:
          seodescription:
            label:
              en: Default description
              nl: Algemene beschrijving
            type: textarea
            buttons: false
            help:
              en: Recomended maximum of 150 characters
              nl: Aangeraden maximum van 150 karakters
          seoimage:
            label:
              en: Default Open Graph image
              nl: Default Open Graph afbeelding
            type: files
            multiple: false
            image:
              ratio: 1200/630
              cover: true
            help:
              en: Shown when sharing this page on WhatsApp, Facebook,...
              nl: Wordt getoond wanneer je deze pagina deelt op WhatsApp, Facebook,...
          aicrawlers:
            label: Allow AI robots
            type: toggles
            default: noindex
            options:
              index:
                en: "Yes"
                nl: Ja
              noindex:
                en: "No"
                nl: Nee
            columns: 2
            help:
              en: Allow AI robots to index and crawl this website
              nl: Laat AI-robots toe om deze website te indexeren
  - width: 2/5
    sections:
      seo:
        type: seo